# Generated by Django 4.1.7 on 2023-03-28 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='date_of_birth',
        ),
        migrations.AddField(
            model_name='customuser',
            name='account_type',
            field=models.CharField(choices=[('cleint', 'cleint'), ('support', 'support'), ('board', 'board')], default='client', max_length=20),
        ),
    ]
