# Generated by Django 4.1.7 on 2023-05-10 14:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("apiapp", "0005_subcategory"),
    ]

    operations = [
        migrations.CreateModel(
            name="Ariticle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("desc", models.CharField(max_length=5000)),
                ("date", models.DateField(auto_now_add=True)),
                (
                    "subcategory",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="apiapp.subcategory",
                    ),
                ),
            ],
        ),
    ]
