# Generated by Django 4.1.7 on 2023-05-10 14:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("apiapp", "0006_ariticle"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Ariticle",
            new_name="Article",
        ),
    ]
