# Generated by Django 4.1.7 on 2023-05-15 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("apiapp", "0007_rename_ariticle_article"),
    ]

    operations = [
        migrations.AddField(
            model_name="supporter",
            name="name",
            field=models.CharField(default="No name", max_length=45),
        ),
    ]
