# Generated by Django 4.1.7 on 2023-05-16 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("apiapp", "0009_alter_supporter_category"),
    ]

    operations = [
        migrations.AlterField(
            model_name="conversation",
            name="title",
            field=models.CharField(default="Chat", max_length=100),
        ),
    ]
