# Generated by Django 4.1.7 on 2023-05-18 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("apiapp", "0011_alter_message_sender"),
    ]

    operations = [
        migrations.AlterField(
            model_name="client",
            name="address",
            field=models.CharField(max_length=45, null=True),
        ),
    ]
