# Generated by Django 4.1.7 on 2023-05-18 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("apiapp", "0012_alter_client_address"),
    ]

    operations = [
        migrations.AlterField(
            model_name="supporter",
            name="name",
            field=models.CharField(default="Kigali", max_length=45),
        ),
    ]
