# Generated by Django 4.1.7 on 2023-05-18 21:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("apiapp", "0013_alter_supporter_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="article",
            name="subcategory",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="apiapp.subcategory",
            ),
        ),
    ]
